server.port=8090

app.http.bot=https://t.me/BigFinaBot
telegram-bot.name=BigFinaBot
telegram-bot.token=6495757238:AAHWAR9Z-QwXRoCUY4tN4GJKwUv5TFSbSao

# Bot db
app.db.bot-db.url=jdbc:postgresql://localhost:5432/postgres
app.db.bot-db.driver=org.postgresql.Driver
app.db.bot-db.user=postgres
app.db.bot-db.password=Sneg3302
app.db.bot-db.pool-size=10

# logging
logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.level.ru.centerinform.webhook=TRACE
logging.file.name=log
